@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package dev.xkmc.modulargolems.compat.materials.legendarymonsters.obliterator;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;