import net.darkhax.curseforgegradle.TaskPublishCurseForge

buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public' }
    }
    dependencies {
        classpath "org.spongepowered:mixingradle:${mixingradle_version}"
        classpath 'org.parchmentmc:librarian:1.+'
    }
}

plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'net.darkhax.curseforgegradle' version '[1.1.24,1.2)'
    id "at.stnwtr.gradle-secrets-plugin" version "1.0.1"
    id "com.modrinth.minotaur" version "2.+"
}

apply plugin: 'maven-publish'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'org.parchmentmc.librarian.forgegradle'

version = "${ll_version}"
group = "dev.kxmc.${modid}"
archivesBaseName = "${modid}"

if (lljij.toBoolean()) jarJar.enable()

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    //mappings channel: 'parchment', version: '1.19.3-2023.03.12-1.19.4'
    mappings channel: 'official', version: "${minecraft_version}"
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'
            mods {
                "${modid}" {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'
            mods {
                "${modid}" {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', "${modid}", '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                "${modid}" {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "${modid}.refmap.json"
    config "${modid}.mixins.json"
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "${modid}",
                "Specification-Vendor"    : "xkmc",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "xkmc",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'            : "${modid}.mixins.json"
        ])
    }
}

java {
    withSourcesJar()
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

if (lljij.toBoolean()) {
    jarJar.enable()
    reobf {
        jarJar {}
    }

    tasks.jarJar.finalizedBy('reobfJarJar')

    tasks.jarJar.configure {
        archiveClassifier.set('')
    }

    jar {
        archiveClassifier.set('slim')
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    compileOnly(annotationProcessor("com.github.llamalad7.mixinextras:mixinextras-common:${mixin_extras_version}"))
    if (rootMod.toBoolean()) {
        implementation(jarJar("com.github.llamalad7.mixinextras:mixinextras-forge:${mixin_extras_version}")) {
            transitive = false
            jarJar.ranged(it, "[${mixin_extras_version},)")
        }
    } else {
        implementation("com.github.llamalad7.mixinextras:mixinextras-forge:${mixin_extras_version}")
    }
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    compileOnly fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")
    if (rootMod.toBoolean()) {
        jarJar(group: 'com.tterrag.registrate', name: 'Registrate', version: "[MC1.20,MC1.21)")
    }
}


repositories {
    flatDir {
        dirs 'libs'
    }
    maven { url 'https://jitpack.io' }
    maven {
        // Location of the maven for vazkii's mods
        name 'blamejared'
        url 'https://maven.blamejared.com'
    }
    maven {
        // Location of the maven for mixed mappings, Registrate, and Flywheel
        name 'tterrag maven'
        url 'https://maven.tterrag.com/'
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url 'https://www.cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://maven.theillusivec4.top/"
    }

    maven { url "https://maven.shadowsoffire.dev/releases" }
    maven {
        url 'https://maven.iafenvoy.com/releases/'
        content {
            includeGroup "com.iafenvoy"
        }
    }
    maven { url = "https://maven.createmod.net" }
}

dependencies {

    implementation fg.deobf("dev.xkmc.l2library:l2library:${l2library_version}-slim")
    implementation fg.deobf("dev.xkmc.l2serial:l2serial:1.2.2")
    runtimeOnly fg.deobf("dev.xkmc.l2modularblock:l2modularblock:1.1.0")
    implementation fg.deobf("dev.xkmc.l2screentracker:l2screentracker:0.1.4")

    implementation fg.deobf("dev.xkmc.l2tabs:l2tabs:0.3.3")

    implementation fg.deobf(jarJar("dev.xkmc.l2itemselector:l2itemselector:0.2.1")) {
        transitive = false
        jarJar.ranged(it, "[0.2.1,)")
    }

    implementation fg.deobf(jarJar("dev.xkmc.l2damagetracker:l2damagetracker:0.3.7")) {
        transitive = false
        jarJar.ranged(it, "[0.3.7,)")
    }

    implementation fg.deobf(jarJar("dev.xkmc.mob_weapon_api:mob_weapon_api:0.2.20")) {
        transitive = false
        jarJar.ranged(it, "[0.2.20,)")
    }

    implementation fg.deobf(jarJar("dev.xkmc.cataclysm_mux:cataclysm_mux:0.0.6")) {
        transitive = false
        jarJar.ranged(it, "[0.0.6,)")
    }

    implementation fg.deobf("dev.xkmc.l2backpack:l2backpack:2.5.7-slim")
    implementation fg.deobf('dev.xkmc.l2complements:l2complements:2.6.1-slim')
    implementation fg.deobf("dev.xkmc.l2hostility:l2hostility:2.5.3-slim")
    implementation fg.deobf("dev.xkmc.golemdungeons:golemdungeons:1.0.2-slim")

    implementation fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}")
    implementation fg.deobf("mezz.jei:jei-${jei_minecraft_version}:${jei_version}")

    runtimeOnly fg.deobf("dev.xkmc.l2artifacts:l2artifacts:2.4.21-slim")
    implementation fg.deobf("dev.xkmc.l2archery:l2archery:2.5.0")
    implementation fg.deobf("dev.xkmc.l2weaponry:l2weaponry:2.5.0")

    implementation fg.deobf('zip.local.blazegear:blazegear:1.4.2')

    runtimeOnly fg.deobf("curse.maven:attributefix-280510:4588114")
    runtimeOnly fg.deobf("curse.maven:bookshelf-228525:4581675")
    runtimeOnly fg.deobf("curse.maven:enchantment-descriptions-250419:4587429")

    //runtimeOnly fg.deobf('curse.maven:appleskin-248787:4440123')

    implementation fg.deobf("curse.maven:create-enchantment-industry-688768:6652836")
    implementation fg.deobf("curse.maven:create-328085:7178761")
    compileOnly(fg.deobf("net.createmod.ponder:Ponder-Forge-1.20.1:1.0.91"))
    compileOnly(fg.deobf("dev.engine-room.flywheel:flywheel-forge-api-1.20.1:1.0.5"))

    implementation fg.deobf("curse.maven:the-twilight-forest-227639:5468648")
    implementation fg.deobf('curse.maven:touhou-little-maid-355044:6657436-sources-6657441')

    runtimeOnly fg.deobf("curse.maven:caelus-308989:4581481")
    runtimeOnly fg.deobf("curse.maven:elytra-slot-317716:4598379")


    implementation fg.deobf("curse.maven:jade-324717:4654448")
    implementation fg.deobf("curse.maven:lionfish-api-1001614:5922047")
    implementation fg.deobf("curse.maven:lendercataclysm-551586:7934870")
    implementation fg.deobf("curse.maven:citadel-331936:5633260")
    implementation fg.deobf("curse.maven:alexs-caves-924854:5848216")
    implementation fg.deobf("curse.maven:ice-and-fire-dragons-264231:5633453")
    implementation fg.deobf("curse.maven:goety-586095:6362347")

    implementation fg.deobf("curse.maven:patchouli-306770:4966125")
    implementation fg.deobf("vazkii.botania:Botania:1.20.1-443-FORGE")
    runtimeOnly fg.deobf("curse.maven:geckolib-388172:6333474")
    runtimeOnly fg.deobf("curse.maven:playeranimator-658587:4587214")
    compileOnly fg.deobf("curse.maven:irons-spells-n-spellbooks-855414:6488484")
    compileOnly fg.deobf("curse.maven:ars-nouveau-401955:4751471")
    implementation fg.deobf("curse.maven:mantle-74924:6105891")
    implementation fg.deobf("curse.maven:tinkers-construct-74072:6111032")
    //implementation fg.deobf("curse.maven:mutil-351914:4824501")
    //implementation fg.deobf("curse.maven:tetra-289712:6096160")

    compileOnly fg.deobf("curse.maven:ewewukeks-musket-mod-354562:5675968")
    runtimeOnly fg.deobf("curse.maven:retro-damage-indicators-1003431:5268035")

    compileOnly fg.deobf("curse.maven:architectury-api-419699:5137938")
    compileOnly fg.deobf("curse.maven:uranus-1010827:6914449")
    compileOnly fg.deobf("curse.maven:jupiter-1072905:7592838")
    compileOnly fg.deobf("curse.maven:iceandfire-ce-1040076:7545797")

    implementation fg.deobf("curse.maven:mowzies-mobs-250498:6224182")
    implementation fg.deobf("curse.maven:ato-405593:5348605")
    implementation fg.deobf("curse.maven:allthemodium-364466:6389531")

    compileOnly fg.deobf("maven.modrinth:goety-revelation:2.1.5")
    implementation fg.deobf("curse.maven:legendary-monsters-944035:6776766")
    implementation fg.deobf("curse.maven:composite-material-982540:6310307")
    //compileOnly fg.deobf("local.zip:RevelationFix:1.20.1")
    runtimeOnly fg.deobf("curse.maven:spark-361579:4738952")

    implementation fg.deobf("dev.shadowsoffire:Placebo:${minecraft_version}-${placebo_version}")
    implementation fg.deobf("dev.shadowsoffire:ApothicAttributes:${minecraft_version}-${attributeslib_version}")
    implementation fg.deobf("dev.shadowsoffire:Apotheosis:${minecraft_version}-${apotheosis_version}")

}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = secrets.get("curseforge_token")
    def mainFile = upload(project.curseforge_project, new File("./build/libs/${modid}-${ll_version}.jar"))
    mainFile.changelog = new File('./changelog.txt').text.split("\n\n\n")[0]
    mainFile.addEnvironment("Client", "Server")
    mainFile.addGameVersion("1.20.1")
    mainFile.addModLoader("Forge","NeoForge")
    mainFile.addRequirement("l2library")
    mainFile.addOptional(
            "blaze-gear",
            "botania",
            "create",
            "jei",
            "l2-archery",
            "l2-backpack",
            "l2-complements",
            "l2hostility",
            "l2weaponry",
            "lendercataclysm",
            "patchouli",
            "the-twilight-forest",
            "alexs-caves",
            "touhou-little-maid",
            "tinkers-construct",
            "ewewukeks-musket-mod",
            "goety",
            "mowzies-mobs",
            "allthemodium",
            "legendary-monsters",
            "composite-material"
    )
    mainFile.releaseType = "release"
    disableVersionDetection()
}

modrinth {
    token = secrets.get("modrinth_token")
    projectId = project.modrinth_project
    versionName = "Modular Golems ${project.ll_version}"
    versionNumber = project.ll_version
    versionType = "release"
    uploadFile = new File("./build/libs/${modid}-${ll_version}.jar")
    gameVersions = ["1.20.1"]
    loaders = ["forge", "neoforge"]
    changelog = new File('./changelog.txt').text.split("\n\n")[0]
    dependencies {
        required.project "l2library"
        optional.project "botania"
        optional.project "create"
        optional.project "jei"
        optional.project "l2archery"
        optional.project "l2backpack"
        optional.project "l2-complements"
        optional.project "l2hostility"
        optional.project "l2weaponry"
        optional.project "l_enders-cataclysm"
        optional.project "patchouli"
        optional.project "touhou-little-maid"
        optional.project "alexs-caves"
    }
}