import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.80'
    id 'net.darkhax.curseforgegradle' version '[1.1.24,)'
    id "at.stnwtr.gradle-secrets-plugin" version "1.0.1"
    id "com.modrinth.minotaur" version "2.+"
}

version = mod_version
group = 'dev.xkmc'

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java {
    withSourcesJar()
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets {
    client {}
    server {}
    data {}
    common {}
}

neoForge {
    // We currently only support NeoForge versions later than 21.0.x
    // See https://projects.neoforged.net/neoforged/neoforge for the latest updates
    version = "${neo_version}"

    // Validate AT files and raise errors when they have invalid targets
    // This option is false by default, but turning it on is recommended
    //validateAccessTransformers = true
    accessTransformers.from "./src/main/resources/META-INF/accesstransformer.cfg"

    runs {
        client {
            client()
        }
        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            neo_version         : neo_version, neo_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors         : mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "${mod_id}",
                "Specification-Vendor"    : "xkmc",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "xkmc",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'            : "${mod_id}.mixins.json"
        ])
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
    maven { // Registrate
        url "https://maven.ithundxr.dev/snapshots"
    }
    maven {
        url = "https://maven.theillusivec4.top/"
        content {
            includeGroup "top.theillusivec4.curios"
        }
    }
    maven {
        // Location of the maven for vazkii's mods
        name 'blamejared'
        url 'https://maven.blamejared.com'
    }
    maven {
        url 'https://www.cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        // Location of the maven that hosts JEI files (and TiC)
        name 'Progwml6 maven'
        url 'https://dvs1.progwml6.com/files/maven'
    }
    maven { url "https://maven.shadowsoffire.dev/releases" }
    maven {
        name = "OctoStudios"
        url = uri("https://maven.octo-studios.com/releases")
    }
    maven { url = "https://maven.createmod.net" }
    mavenLocal();
}

dependencies {
    compileOnly "com.tterrag.registrate:Registrate:${registrate_version}"

    implementation "dev.xkmc:l2serial:${l2serial_ver}"
    implementation "dev.xkmc:l2modularblocks:${l2modularblocks_ver}"
    implementation "dev.xkmc:l2core:${l2core_ver}"
    implementation "dev.xkmc:l2menustacker:${l2menustacker_ver}"
    implementation "dev.xkmc:l2itemselector:${l2itemselector_ver}"
    implementation "dev.xkmc:l2library:${l2library_ver}-slim"

    implementation jarJar(group: 'dev.xkmc', name: 'l2tabs', version: "[${l2tabs_ver},)")
    implementation jarJar(group: 'dev.xkmc', name: 'l2damagetracker', version: "[${l2damagetracker_ver},)")
    implementation jarJar(group: 'dev.xkmc', name: 'mob_weapon_api', version: "[${mob_weapon_api_ver},)")

    implementation "dev.xkmc:l2backpack:${l2backpack_ver}"
    implementation "dev.xkmc:l2complements:${l2complements_ver}"
    implementation "dev.xkmc:l2weaponry:${l2weaponry_ver}"
    implementation "dev.xkmc:l2magic:${l2magic_ver}"
    implementation "dev.xkmc:fast_projectile_api:${fast_projectile_api_ver}"
    implementation "dev.xkmc:l2hostility:${l2hostility_ver}-slim"
    implementation "vazkii.patchouli:Patchouli:${patchouli_ver}"

    implementation "dev.xkmc:better_creative_tabs:0.1.0"
    implementation "dev.xkmc:more_wolf_armors:0.1.3"

    implementation "mezz.jei:jei-${jei_minecraft_version}:${jei_version}"
    implementation "top.theillusivec4.curios:curios-neoforge:${curios_version}"
    implementation "curse.maven:the-twilight-forest-227639:5699076"
    implementation "curse.maven:touhou-little-maid-355044:6657437"
    implementation "dev.xkmc:l2archery:${l2archery_ver}"

    implementation "curse.maven:lionfish-api-1001614:6168249"
    implementation "curse.maven:lendercataclysm-551586:7578941"
    implementation "curse.maven:create-328085:6624071"
    implementation("curse.maven:create-enchantment-industry-688768:6431470")
    implementation "curse.maven:create-dragons-plus-1216624:6440339"

    //compileOnly("com.simibubi.create:create-1.21.1:6.0.5-92") { transitive = false }
    compileOnly("net.createmod.ponder:Ponder-NeoForge-1.21.1:1.0.39") { transitive = false }
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-1.21.1:1.0.0-10")

    implementation "curse.maven:jupiter-1072905:7592856"
    implementation "curse.maven:uranus-1010827:6979353"
    implementation "curse.maven:iceandfire-ce-1040076:7524985"
    implementation "curse.maven:architectury-api-419699:5786327"
    implementation "curse.maven:geckolib-388172:6304958"
    //implementation "curse.maven:ato-405593:6118610"
    implementation "curse.maven:allthemodium-364466:6389532"
    implementation "curse.maven:cloth-config-348521:5729127"
    implementation "curse.maven:ewewukeks-musket-mod-354562:5805570"
    implementation "curse.maven:mowzies-mobs-250498:6700443"

    testImplementation "com.mojang:datafixerupper:8.0.16"
    testImplementation "com.google.guava:guava:32.1.2-jre"

}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = secrets.get("curseforge_token")
    def mainFile = upload(project.curseforge_project, new File("./build/libs/${mod_id}-${mod_version}.jar"))
    mainFile.changelog = new File('./changelog.txt').text.split("\n\n\n")[0]
    mainFile.addEnvironment("Client", "Server")
    mainFile.addGameVersion("1.21.1")
    mainFile.addModLoader("NeoForge")
    mainFile.addRequirement("l2library")
    mainFile.addOptional(
            "blaze-gear",
            "botania",
            "create",
            "jei",
            "l2-archery",
            "l2-backpack",
            "l2-complements",
            "l2hostility",
            "l2weaponry",
            "lendercataclysm",
            "patchouli",
            "the-twilight-forest",
            "touhou-little-maid",
            "allthemodium")
    mainFile.releaseType = "release"
    disableVersionDetection()
}

modrinth {
    token = secrets.get("modrinth_token")
    projectId = project.modrinth_project
    versionName = "Modular Golems ${project.mod_version}"
    versionNumber = project.mod_version
    versionType = "release"
    uploadFile = new File("./build/libs/${mod_id}-${mod_version}.jar")
    gameVersions = ["1.21.1"]
    loaders = ["neoforge"]
    changelog = new File('./changelog.txt').text.split("\n\n")[0]
    dependencies {
        required.project "l2library"
        optional.project "botania"
        optional.project "create"
        optional.project "jei"
        optional.project "l2archery"
        optional.project "l2backpack"
        optional.project "l2-complements"
        optional.project "l2hostility"
        optional.project "l2weaponry"
        optional.project "l_enders-cataclysm"
        optional.project "patchouli"
        optional.project "touhou-little-maid"
    }
}