# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=26.1.2
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[26.1.2,26.2)
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=26.1.2.87

## Mod Properties
mod_id=modulargolems
mod_name=Modular Golems
mod_license=LGPL-2.1
mod_version=26.1.2.0+11+dungeon
mod_group_id=dev.xkmc
mod_authors=lcy0x1
mod_description=Golems

jei_minecraft_version = 26.1.2-neoforge
jei_version = 29.5.0.28
l2serial_ver = 26.1.0.9
registrate_ver = MC26.1-1.5.0
l2core_ver = 26.1.2.0+23
l2menustacker_ver = 26.1.2.1
l2tabs_ver = 26.1.2.1
l2damagetracker_ver = 26.1.2.0+2
l2itemselector_ver = 26.1.2.0+6
l2modularblock_ver = 26.1.0.0
mob_weapon_api_ver = 26.1.2.0+4
golemdungeons_ver = 26.1.2.0+6
better_creative_tabs_ver = 26.1.0.1

curios_version = 15.0.0-beta.2+26.1.2