org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mixingradle_version = 0.7-SNAPSHOT
mixin_version = 0.8.5

minecraft_version = 1.20.1
forge_version = 47.4.10
mixin_extras_version = 0.2.0-beta.8
registrate_version = MC1.20-1.3.11
jei_minecraft_version = 1.20.1-forge
jei_version = 15.20.0.104
curios_version = 5.9.1+1.20.1

modid = modulargolems
ll_version = 2.6.32+2
lljij = true
rootMod = false

l2library_version = 2.5.3
patchouli_version = 1.20.1-80-FORGE-SNAPSHOT
attributeslib_version=1.3.7
apotheosis_version=7.4.8
placebo_version=8.6.3

curseforge_project = 690937
modrinth_project = gtGDlsAD