modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"
[[dependencies.${ mod_id }]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "l2library"
type = "required"
versionRange = "${project.l2library_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "create"
type = "optional"
versionRange = "[6.0.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "iceandfire"
type = "optional"
versionRange = "[2.0-beta.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "cataclysm"
type = "optional"
versionRange = "[3.16,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "l2complements"
type = "optional"
versionRange = "[3.1.2,)"
ordering = "NONE"
side = "BOTH"