@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package dev.xkmc.projectile_api.integration.l2complements;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;