@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package dev.xkmc.projectile_api.integration.twilightforest;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;